language: java
env:
  global:
  - secure: BFwR2iCNJksNCmhPcypi1y5FW6v4rGjKh34D3VKcHnSPSCKEVHtaVhuiNLx6VImo1BsHEmcJd+8fficAJ7QJw1KrOxj4kOZ0D3OBrIZ//wyOWOLtXO3Ztf1UOxAREEBOmQhw44ZYbL1qAnlAP4M+6NmkTiS3SqPsG3yRvyhAgBAyYi5Lop7JGwf5UYBrz142RrNKmdYnqKwut29nXFg/f9CIXmXZJ/ZXqVQ83zsijSBACsMCc7O2asZ/aTYgI5QODzZLYK1iL+1DZaOtlmWIAgtZO0nwMT2JaqfA3TyTi5pWbPhOOXrkPccDPfDaBNaQ7s4eCkTXvHIcayjzZe9OZGCgwh900WS5lCrH5MmD+1O6hE8Dg5X9aPG2o/fzJqvIr43XcL4zXIgy3nxSFOtN4giXXcCbfp+eVbWB/pPu+7Dfj5c20JTVdS8DDFz+E5QtCz8x3EdLFTiEdClxCREEJSjUTx1TWtMKVe9NQZWTNnVebiR4FAg/Mn5D8Rl6SCcFHOH6YKqyXmM+opceAk9N2kJOqXNo2eD3YCptwQGZUAmWXPs990Yg2/g/HmGreEfP4KSnCzmoOX3wz5N14Py+8A1T82LviBgye/Ssfkep9+0VK26MWQEXX3zYQi/uNFGSz6ZacB5venDKk/EpfDscp84zQLAa1hsCz/1FO1tCJ+w=
  - secure: g0OTJbFLIcxPMv+kR8r4Ei1kSWXg8oXsna4ulk8NGpF93c5bviyMMuSZWJidkqFQWeCqMBgBXRHvtFvwQkWjRhi7k8xSzOIM+9qwJjSO/znty87kUx+nFv+Dd6APV1oMtYFq5kR1fZRkeGkLSSacUeU/O8lwGnSGIYcQqoqV0hLyorEOA7/K/qnTANiZZs2ACd7CtoqOR1oIqtqsnlT/BzboyChQOsbz5PXWohSIdmCN8gnopviqDmDNRAQZ7rRonYcTrjFlxye+ZK8Cls89vhIM+eH42sK59NUE3RxXSOPAZDn/ptgsJxkXbQoCOSTaYtDdtmWrDjyIazdGy9bBwKfidRITP3vLWSg3Aj3P7DfetzL4/RbmTANjP6mMOr77q6RPHb4NV1BD7/K90y7C5q+GMEGfi5IDt5XS5eTPi2dSXGqbMB5y1zaQP+IM1+5PV8DCc9PoVf33NN8I0jDNjtArRuWpaFn5Sp8r6GZTNS4lks6/0L1ZXM1a6DRdfkCuGXppoJ31SCrQsR0HE4ByCaoJWhdNhxgcOtFxB12eGfFsmfAMXrvmYKsuME+r0n8MEw9Eg6hSMdgQQOGVNoeuwQW+8jaLwM8FAWS9jqjrLBZ2Fk8T4kcA49JslFcw+Lqv37new9CDc/KBHqta7P5MsXURaMojnE7wq4yyAl++gGI=
script: mvn -B deploy -DskipTests -s mvnsettings.xml
deploy:
  provider: releases
  api_key:
    secure: JQKvIazVP4GBdj8PZnwpR8bpWZC4ivWFrCLAbg2W0DOaIxNPklCkre14XpGRkMPjVdsbl/EYxwEZ1wSjSGOHiP7i8G+hkv8e5eSXB7J/jl/SkTaMDbccs6kyIFeUx6W4phTH6vhYpcRuD+09dskVIanB5u1wFewQz3j7gxXNbydGJDq5Ff36RTtNQjvdoYC4BxQHtYB3T0JxYICyHfzzfN48s1HpUlTpgsphrP+f+qBwZM3roLkyTws14YJH8pNYlE9ywjRltOspOsh/+Y2XRNtQ67ecGJJnQU7ln2pz+GXBphoM7De23wsrSs+4c73Z3oNNFkv6VXVRXKlP0fTdnBdB8+9J60vHSJfaz90VEKE5UH5kv3+HGvEOi6SBZVgPBtwbuCwImAnRYz2KIEZql3rygIwUapLMB/oGfYPONZid/pJv0Hkamv7+0xLxrFZI3yHBg89ZMSgOSrjjMjqw05St/ZLu8C//FKBteKHV6mvUeAP5aivs+pr8gCTW3TCfiq8coYsshzkTuWBQesbQFaOppG/p8wSI74N88e11Q32BTstttyWT+in//ZJ2hJnlCjoAUN4Giot9H6BzZUK5wEYbS4OBesFmgQ8K02ZK1wuKYVQGBEWfV8nKbavXNEh69C6U4W+9cf6Kw6jmF8JaSsu0RpN4/uAUyYuTFRVKIok=
  file_glob: true
  file:
    - searchui-frontend/target/*.zip
    - searchui-module/target/*.zip
    - searchui-servlet/target/*.war
  skip_cleanup: true
  prerelease: true
  on:
    repo: attivio/searchui
    branch: 5.5.1-release
